config/routes.rb
Rails.application.routes.draw do
  get "contact/show"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }
  # Ruta raíz de la aplicación
  root "home#index"
  get "about", to: "home#about", as: "about"
  get "contact", to: "contact#show"

  namespace :admin do
    get "stock", to: "products#stock", as: "stock"
    patch "products/:id/update_stock", to: "products#update_stock", as: "update_stock_product"
  end

  resources :orders, only: [ :index, :create ] do
    member do
      patch :change_status
    end
  end

  # Rutas para productos (index, show y favorito)
  resources :products, only: [ :index, :show, :edit, :update, :destroy, :new, :create ] do
    member do
      post "favorite"    # Agregar a favoritos
      delete "unfavorite" # Eliminar de favoritos
    end
  end

  resources :favorites, only: [ :index ]  # Ruta para listar los favoritos

  resources :categories, only: [ :show ]


  # Ruta para una acción add en el mismo controlador, que se usará para agregar productos al carrito.
  resource :cart, only: [ :show ] do
    post "add/:product_id", to: "carts#add", as: "add_to_cart"       # Agregar al carrito
    get "checkout", on: :member                                      # Página de checkout
    match "complete", to: "carts#complete", as: "complete_cart", via: [ :get, :post ] # Finalizar compra
    delete "remove/:product_id", to: "carts#remove", as: "remove_from_cart" # Eliminar del carrito
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @products = Product.all
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<!-- app/views/home/about.html.erb -->
<div class="container mt-5">
  <h1 class="text-center mb-4">Sobre Nosotros</h1>

  <div class="row">
      <h3 class="text-center">Jaka'ay'u</h3>
      <p class="text-center">Somos una microempresa familiar que se dedica a mezclar la tradición y la cultura, de</p> <p class="text-center">manera artesanal y con mucho amor. En cada uno de nuestros productos se refleja el</p><p class="text-center"> esfuerzo y la pasión de nuestra familia para ofrecer lo mejor a nuestros clientes.</p>
      <p class="text-center">Agradecemos profundamente tu preferencia y apoyo. Cada compra que realizas nos </p> <p class="text-center">acerca a nuestra misión de preservar nuestras tradiciones y compartirlas con el mundo.</p>
    </div>

    <!-- Imagen entre las dos secciones -->
    <div class="col-12 my-4">
      <img src="<%= asset_path('WhatsApp Image 2024-11-18 at 00.34.58.jpeg') %>" alt="Imagen de Jaka'ay'u" class="img-fluid w-100 rounded">
    </div>

    <div class="col-md-6">
      <h3 class="text-center">La Familia González Martínez</h3>
      <p class="text-center">Somos la Familia González Martínez, quienes con mucho cariño y dedicación nos encargamos de que cada producto tenga el sello único de nuestra artesanía. Nuestra historia está llena de valores familiares y compromiso con la cultura local, y te invitamos a ser parte de ella.</p>
      <p class="text-center"><strong>¡Gracias por tu preferencia!</strong></p>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="container-fluid mt-4">
  <% if current_user&.admin? %>
    <%= link_to "Nuevo Producto", new_product_path, class: "btn btn-success mb-3" %>
  <% end %>
<div class="row row-cols-1 row-cols-md-3 g-4">
  <% if @products.any? %>
    <% @products.each do |product| %>
      <div class="col-md-3">
        <div class="card h-100 text-center">
          <div class="card-body">
            <%= link_to product_path(product) do %>
              <%= image_tag "products/#{product.image_url}", class: "card-img-top" if product.image_url.present? %>
              <h5 class="card-title"><%= product.name %></h5>
            <% end %>
            <p class="card-text"><%= number_with_delimiter(product.price.to_i, delimiter: ".", separator: "") %> Gs.</p>
            
            <% if product.agotado? %>
              <p class="text-danger"><strong>Agotado</strong></p>
            <% else %>
              <p class="text-success"><strong>En stock</strong></p>
            <% end %>
              <% if current_user&.admin? %>
                <div class="mt-2 d-inline-flex gap-2">
                  <%= link_to "Editar", edit_product_path(product), class: "btn btn-success btn-sm" %>
              <%= button_to "Eliminar", product_path(product), 
                            method: :delete, 
                            data: { confirm: "¿Estás seguro de que quieres eliminar este producto?" }, 
                            class: "btn btn-danger btn-sm" %>

                </div>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>No hay productos que coincidan con la búsqueda.</p>
    <% end %>
  </div>
</div>