config/routes.rb
Rails.application.routes.draw do
  get "contact/show"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    passwords: "users/passwords",
    confirmations: "users/confirmations",
    unlocks: "users/unlocks"
  }
  # Ruta raíz de la aplicación
  root "home#index"
  get "about", to: "home#about", as: "about"
  get "contact", to: "contact#show"

  namespace :admin do
    get "stock", to: "products#stock", as: "stock"
    patch "products/:id/update_stock", to: "products#update_stock", as: "update_stock_product"
  end

  resources :orders, only: [ :index, :create ] do
    member do
      patch :change_status
    end
  end

  # Rutas para productos (index, show y favorito)
  resources :products, only: [ :index, :show, :edit, :update, :destroy, :new, :create ] do
    member do
      post "favorite"    # Agregar a favoritos
      delete "unfavorite" # Eliminar de favoritos
    end
  end

  resources :favorites, only: [ :index ]  # Ruta para listar los favoritos

  resources :categories, only: [ :show ]


  # Ruta para una acción add en el mismo controlador, que se usará para agregar productos al carrito.
  resource :cart, only: [ :show ] do
    post "add/:product_id", to: "carts#add", as: "add_to_cart"       # Agregar al carrito
    get "checkout", on: :member                                      # Página de checkout
    match "complete", to: "carts#complete", as: "complete_cart", via: [ :get, :post ] # Finalizar compra
    delete "remove/:product_id", to: "carts#remove", as: "remove_from_cart" # Eliminar del carrito
  end
end

app/models/product.rb
class Product < ApplicationRecord
  # Validaciones
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :stock, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  # Relaciones
  belongs_to :category
  has_many :favorites, dependent: :destroy
  has_many :favorited_by_users, through: :favorites, source: :user
  has_many :order_products
  has_many :orders, through: :order_products

  def agotado?
    stock.to_i.zero?
  end

  # Método para restar stock de forma segura
  def reduce_stock!(quantity)
    if stock >= quantity
      self.stock -= quantity
      save!
    else
      raise "Stock insuficiente para #{name}"
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin! # Asegúrate de proteger estas rutas

  def stock
    @products = Product.all
  end

  def update_stock
    product = Product.find(params[:id])
    new_stock = params[:stock].to_i

    if new_stock >= 0
      product.update(stock: new_stock)
      flash[:notice] = "Stock actualizado correctamente."
    else
      flash[:alert] = "El stock no puede ser negativo."
    end

    redirect_to admin_stock_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :check_admin, only: [ :edit, :update ]

  def index
    if params[:query].present?
      @products = Product.where("name LIKE ?", "%#{params[:query]}%")
    else
      @products = Product.all
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def favorite
    @product = Product.find(params[:id])

    # Verifica si el producto ya está en los favoritos del usuario
    if current_user.favorite_products.include?(@product)
      flash[:alert] = "#{@product.name} Ya está en tus favoritos."
    else
      current_user.favorites.create(product: @product)
      flash[:notice] = "#{@product.name} Se agregó tus favoritos."
    end

    # Redirige de vuelta a la vista del producto
    redirect_to product_path(@product)
  end

  def unfavorite
    @product = Product.find(params[:id])

    # Elimina el producto de los favoritos del usuario
    if current_user.favorite_products.include?(@product)
      current_user.favorites.find_by(product: @product).destroy
      flash[:notice] = "#{@product.name} Ha sido eliminado de tus favoritos."
    else
      flash[:alert] = "#{@product.name} No estaba en tus favoritos."
    end

    # Redirige según el parámetro 'redirect_to_favorites'
    if params[:redirect_to_favorites]
      redirect_to favorites_path
    else
      redirect_to product_path(@product)
    end
  end

  # Acción para guardar el producto en la base de datos
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path, notice: "Producto creado exitosamente."
    else
      flash[:error] = @product.errors.full_messages.join(", ")
      render :new
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:success] = "Producto eliminado correctamente."
      redirect_to root_path
    else
      flash[:error] = "No se pudo eliminar el producto."
      redirect_to root_path
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to root_path, notice: "Producto actualizado correctamente."
    else
      # Mostrar los errores en el formulario
      flash[:error] = @product.errors.full_messages.join(", ")
      render :edit
    end
  end

  private

  def check_admin
    redirect_to root_path, alert: "No tienes permisos para realizar esta acción." unless current_user&.admin?
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :category_id, :image_url).tap do |whitelisted|
      # Limpiar y convertir el precio a un número entero
      whitelisted[:price] = whitelisted[:price].to_s.gsub(",", "").to_i
    end
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<div class="product-details">
  <h1>Editar Producto: <%= @product.name %></h1>
  
  <% if flash[:error].present? %>
    <div class="alert alert-danger">
      <%= flash[:error] %>
    </div>
  <% end %>

  <div class="product-container">
    <div class="product-image">
      <%= image_tag "products/#{@product.image_url}" if @product.image_url.present? %>
      <div class="form-group">
        <%= label_tag :image_url, "Nueva imagen" %>
        <%= text_field_tag :image_url, @product.image_url, class: "form-control" %>
      </div>
    </div>

    <div class="product-info">
      <%= form_for @product do |f| %>
        <div class="form-group">
          <%= f.label :name, "Nombre del Producto" %>
          <%= f.text_field :name, class: "form-control" %>
          <% if @product.errors[:name].any? %>
            <div class="error-message">
              <%= @product.errors[:name].join(", ") %>
            </div>
          <% end %>
        </div>

        <div class="form-group">
          <%= f.label :description, "Descripción" %>
          <%= f.text_area :description, class: "form-control" %>
          <% if @product.errors[:description].any? %>
            <div class="error-message">
              <%= @product.errors[:description].join(", ") %>
            </div>
          <% end %>
        </div>

<div class="form-group">
  <%= f.label :price, "Precio" %>
  <%= f.text_field :price, class: "form-control" %> <!-- Cambié a text_field -->
  <% if @product.errors[:price].any? %>
    <div class="error-message">
      <%= @product.errors[:price].join(", ") %>
    </div>
  <% end %>
</div>


        <div class="form-group">
          <%= f.submit "Aceptar Cambios", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container-fluid mt-4">
  <div class="row row-cols-1 row-cols-md-3 g-4">
<% if @products.any? %>
  <% @products.each do |product| %>
    <div class="col-md-3">
      <div class="card h-100 text-center">
        <div class="card-body">
          <%= link_to product_path(product) do %>
            <%= image_tag "products/#{product.image_url}", class: "card-img-top" if product.image_url.present? %>
            <h5 class="card-title"><%= product.name %></h5>
          <% end %>
          <p class="card-text">$<%= product.price %></p>

          <% if product.agotado? %>
            <p class="text-danger"><strong>Agotado</strong></p>
          <% else %>
            <p class="text-success"><strong>En stock</strong></p>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
<% else %>
  <p>No hay productos que coincidan con la búsqueda.</p>
<% end %>

  </div>
</div>

app/views/products/new.html.erb
<h1>Crear Producto</h1>

<%= form_with model: @product, local: true do |form| %>
  <div class="mb-3">
    <%= form.label :name, "Nombre del Producto" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, "Descripción" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :price, "Precio" %>
    <%= form.number_field :price, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :category_id, "Categoría" %>
    <%= form.select :category_id, Category.all.collect { |c| [c.name, c.id] }, {}, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :image_url, "URL de la Imagen" %>
    <%= form.text_field :image_url, class: "form-control" %>
  </div>

  <%= form.submit "Crear Producto", class: "btn btn-primary" %>
<% end %>

<%= link_to "Volver", root_path, class: "btn btn-secondary mt-3" %>

app/views/products/show.html.erb
<div class="product-details">
  <h1><%= @product.name %></h1>
  <div class="product-container">
    <div class="product-image">
      <!-- Muestra la imagen del producto -->
      <%= image_tag "products/#{@product.image_url}" if @product.image_url.present? %>
    </div>

    <div class="product-info">
      <p><%= @product.description %></p>
      <p><strong><%= number_with_delimiter(@product.price.to_i, delimiter: ".", separator: "") %> Gs.</strong></p>
      
      <!-- Mostrar mensaje de "Agotado" si no hay stock -->
      <% if @product.agotado? %>
        <p class="text-danger"><strong>Producto agotado</strong></p>
      <% else %>
        <!-- Seleccionar cantidad -->
        <%= form_with url: add_to_cart_cart_path(product_id: @product.id), method: :post, local: true do |form| %>
          <div class="form-group">
            <label for="quantity"></label>
            <%= form.number_field :quantity, in: 1..@product.stock, step: 1, value: 1, class: 'form-control' %>
          </div>
          <!-- Botón para agregar al carrito -->
          <%= button_to 'Agregar al Carrito', add_to_cart_cart_path(product_id: @product.id), method: :post, class: 'btn btn-success' %>
        <% end %>
      <% end %>
      
      <!-- Mostrar el botón dependiendo si el producto está en favoritos -->
      <% if current_user.favorite_products.include?(@product) %>
        <!-- Si está en favoritos, mostrar el botón para eliminarlo -->
        <%= button_to "Eliminar de favoritos", unfavorite_product_path(@product), method: :delete, class: "btn btn-danger" %>
      <% else %>
        <!-- Si no está en favoritos, mostrar el botón para agregarlo -->
        <%= button_to "Favorito ❤️", favorite_product_path(@product), method: :post, class: "btn btn-secondary" %>
      <% end %>
    </div>
  </div>
</div>
      <!-- Mostrar el mensaje de flash si está presente -->
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <%= flash[:alert] %>
        </div>
      <% end %>
  </div>
</div>